name: Deploy to EC2

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /var/www
          git pull origin main
